# Generated by Django 4.2.13 on 2024-07-29 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birth_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
