# Generated by Django 4.2.13 on 2024-07-05 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0005_familiar_is_active_patient_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Peso')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('pulse', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Pulso')),
                ('temperature', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Temperatura')),
                ('breathing', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Respiracion')),
                ('systolic', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Presion Sistolica')),
                ('diastolic', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Presion Diastolica')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patient.patient', verbose_name='Paciente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'expedient',
                'verbose_name_plural': 'expedients',
            },
        ),
    ]
