# Generated by Django 4.2.13 on 2024-06-28 19:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0004_alter_familiar_phone_alter_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Peso')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('pulse', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Pulso')),
                ('temperature', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Temperatura')),
                ('breathing', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Respiracion')),
                ('systolic', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Presion Sistolica')),
                ('diastolic', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Presion Diastolica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patient.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'expedient',
                'verbose_name_plural': 'expedients',
            },
        ),
    ]
