# Generated by Django 4.2.13 on 2024-07-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
