# Generated by Django 4.2.13 on 2024-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='familiar',
            field=models.ManyToManyField(blank=True, to='patient.familiar'),
        ),
    ]
