# Generated by Django 4.2.13 on 2024-06-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_familiar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familiar',
            options={'verbose_name': 'familiar', 'verbose_name_plural': 'familiars'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'patient', 'verbose_name_plural': 'patiesnts'},
        ),
    ]
