# Generated by Django 4.2.13 on 2024-07-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_familiar_phone_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
