# Generated by Django 4.2.13 on 2024-07-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_familiar_is_active_patient_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
