# Generated by Django 4.2.13 on 2024-07-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0001_initial'),
        ('patient', '0006_alter_familiar_address_alter_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='allergies', to='allergies.allergies'),
        ),
    ]
