# Generated by Django 4.2.13 on 2024-07-11 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'allergie',
                'verbose_name_plural': 'allergies',
            },
        ),
    ]
